django/django_project/bank/urls.py
from django.conf.urls import url,include
from . import views
from django.contrib.auth import views as auth_views

from django.views.decorators.csrf import csrf_exempt

from django.urls import path, re_path

app_name = 'bank'

urlpatterns = [
    
    re_path(r'^$',(views.index),name='index'),
    
    re_path(r'^logout/$', auth_views.LogoutView, {'next_page': '/'}, name='logout'),
    re_path(r'^signup/$',views.signup,name='signup'),
    
    re_path(r'^login/$',views.login,name='login'),
    re_path(r'^add/$',views.add,name='add'),
    re_path(r'^del/$',views.del_ca,name='del_ca'),

    re_path(r'^dashboard/(?P<string>.+)/$',views.dashboard,name='dashboard'),
    re_path(r'^current-affairs/detail/(?P<user_year_month>.+)/(?P<user_page_no>[0-9]+)/$',views.ca,name='ca'),
    re_path(r'^current/(?P<string>.+)/(?P<params>[0-9]+)/$',views.current,name='current'),
    re_path(r'^cuttent_affirs/(?P<string>.+)/$',views.cuttent_affirs_single,name='cuttent_affirs'),
    re_path(r'^english/word/(?P<string>.+)/(?P<no>[0-9]+)/$',views.word,name='word'),
    re_path(r'^math/(?P<string>.+)/(?P<params>[0-9]+)/$',views.math_all,name='math'),
    re_path(r'^job/(?P<string>.+)/(?P<after_string>.+)/(?P<params>[0-9]+)/$',views.job_view,name='job'),
    re_path(r'^reasoning/(?P<string>.+)/(?P<params>[0-9]+)/$',views.reasoning_all,name='reasoning'),
    re_path(r'^reasoning/(?P<string>.+)/$',views.reasoning_single,name='reasoning_single'),
    re_path(r'^closetest/(?P<string>.+)/(?P<params>[0-9]+)/$',views.close_all,name='close'),
     re_path(r'^error_correction/(?P<string>.+)/(?P<params>[0-9]+)/$',views.error_all,name='error'),


     re_path(r'^activate/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,20})/$',
        views.activate, name='activate'),

    re_path(r'^formula/(?P<string>.+)/$',views.formula,name='formula'),
    
    re_path(r'^gktoday/(?P<subject>.+)/(?P<folder>.+)/(?P<html>.+)/(?P<no>[0-9]+)/$',views.gk,name='gk'),
    re_path(r'^gk/(?P<subject>.+)/$',views.gk_index,name='gk_index'),
    
    re_path(r'^current-affairs/mcq/(?P<user_year_month>.+)/(?P<user_page_no>[0-9]+)/$',views.mcq_current,name='mcq_current'),
    re_path(r'^subject/(?P<subject>.+)/(?P<topic>.+)/(?P<subtopic>.+)/(?P<chapter>.+)/(?P<user_page_no>[0-9]+)/$',views.subject,name='history'),
    re_path(r'^database/$',views.database,name='database'),
    
    
    
]

django/django_project/django_project/urls.py
#from django.conf.urls import patterns, include, url
from django.urls import path, re_path

from django.contrib import admin
from bank.admin import admin_site
from django.conf.urls import url
from django.urls import path

from django.conf import settings
from django.conf.urls.static import static
import bank
from django.conf.urls import url,include
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
admin.autodiscover()

urlpatterns = [
    re_path(r'^admin/', admin_site.urls),
    re_path(r'^genai/', include('genai.urls')),
    re_path(r'^mocktest/', include('mocktest.urls')),
    path('api/', include('students.urls')),
    re_path(r'^', include('bank.urls')),
       
]
urlpatterns += staticfiles_urlpatterns() 
urlpatterns +=static(settings.STATIC_URL,document_root=settings.STATIC_ROOT)
urlpatterns +=static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

django/django_project/this forlder is a back up of django_project/urls.py
from django.contrib import admin
from django.urls import path
from . import views

urlpatterns = [
    path('', views.index, name='index'),
    path('admin/', admin.site.urls)
]

django/django_project/bank/forms.py
from django import forms
from django.contrib.auth.models import User


class FaqForm(forms.ModelForm):
  answer = forms.CharField( widget=forms.Textarea(attrs={'rows': 5, 'cols': 100}))


class UserForm(forms.ModelForm):
    password = forms.CharField(widget=forms.PasswordInput(attrs={'class' : 'form-control','placeholder':"password"}))
    username=forms.CharField(widget=forms.TextInput(attrs={'class' : 'form-control','placeholder':"username"}))
    email=forms.CharField(widget=forms.TextInput(attrs={'class' : 'form-control','placeholder':"email"}))

    
    class Meta:
        model = User
        fields = ['username', 'email', 'password']
    def clean(self):
        cleaned_data = super(UserForm, self).clean()
        email1 = cleaned_data.get("email")
        
        email2 = User.objects.filter(email=email1)
        if User.objects.exclude(pk=self.instance.pk).filter(email=email1).exists():
            raise forms.ValidationError(
                    
                    'Email Aready Exists'+str(email2)
                )
class Login(forms.ModelForm):
    password = forms.CharField(widget=forms.PasswordInput(attrs={'class' : 'form-control','placeholder':"password"}))
    username=forms.CharField(widget=forms.TextInput(attrs={'class' : 'form-control','placeholder':"username"}))
    
    class Meta:
        model = User
        fields = ['username', 'password']
  

django/django_project/bank/views.py
from __future__ import unicode_literals
from django.shortcuts import render
from django.views.generic import TemplateView,RedirectView
from .models import current_affairs_slide
from django.http import HttpResponseRedirect,HttpResponse
from django.urls import reverse,reverse_lazy, resolve
from django.shortcuts import redirect

from django.template import RequestContext
import urllib
from .models import current_affairs_slide
from .models import total
from .models import total_english
from .models import total_math
from .models import total_english
from .models import math
from .models import user_save
from .models import total_reasoning
from .models import total_close
from .models import close
from .models import topic
from .models import reasoning
import datetime
from .models import total_error
from .models import error
from .models import currentaffairs_descriptive
from .models import the_hindu_word_list1
from .models import the_economy_word_list1
from .models import the_hindu_word_list2
from .models import the_economy_word_list2
from .models import the_economy_word_Header2
from .models import the_economy_word_Header1
from .models import the_hindu_word_Header1
from .models import the_hindu_word_Header2
from .models import total_job
from .models import total_job_state
from .models import total_job_category
from .models import total_mcq
from .models import home
from .models import currentaffairs_mcq
from .models import currentaffairs_mcq_info_2018
from .models import currentaffairs_mcq_info_2019
from .models import currentaffairs_descriptive_info_2018
from .models import currentaffairs_descriptive_info_2019
from .models import total_history
from .models import history
from .models import total_polity
from .models import polity
from .models import total_geography
from .models import geography
from .models import total_economics
from .models import economics
from .models import total_physics
from .models import physics
from .models import total_chemistry
from .models import chemistry
from .models import total_biology
from .models import biology

import json
from django.contrib.auth import authenticate
from django.contrib.auth import login as auth_login
from django.contrib.auth import logout

from .forms import UserForm
from django.core import serializers
from django.views.decorators.csrf import csrf_protect
from django.db import models

from django.contrib.auth.models import User
from .forms import Login
import sys
import os
from django.urls import reverse
import datetime as dt     
import time 
from datetime import timedelta
from datetime import date
from .models import job

from django.contrib.sites.shortcuts import get_current_site
from django.utils.encoding import force_bytes, force_text
from django.utils.http import urlsafe_base64_encode, urlsafe_base64_decode
from django.template.loader import render_to_string
#from .tokens import account_activation_token
from django.contrib.auth.models import User
from django.core.mail import EmailMessage

from time import gmtime, strftime
# Create your views here.

def index(request):
    userform = UserForm(request.POST or None)
    login = Login(request.POST or None)
    hindu=0
    e=0
    header1=None
    header2=None
    header_e1=None
    header_e2=None
    word1_obj=home.objects.values('word1_day')[0]
    word1_day=(word1_obj['word1_day'])
    
    word2_obj=home.objects.values('word2_day')[0]
    word2_day=(word2_obj['word2_day'])

    word_e1_obj=home.objects.values('word_e1_day')[0]
    word_e1_day=(word_e1_obj['word_e1_day'])

    word_e2_obj=home.objects.values('word_e2_day')[0]
    word_e2_day=(word_e2_obj['word_e2_day'])

    
    word1 = the_hindu_word_list1.objects.values('word','meaning','synonym','example','word_img').filter(day=word1_day)
    word2 = the_hindu_word_list2.objects.values('word','meaning','example','word_img','synonym').filter(day=word2_day)
    if(word1.count()>0):
        hindu=1
        header1 = the_hindu_word_Header1.objects.values('Heading_for_list1','link').filter(day=word1_day)
        if(header1==None):
            header1=None
    else:
        word1=None
            
                
    if(word2.count()>0):
        hindu=2
        header2 = the_hindu_word_Header2.objects.values('Heading_for_list2','link').filter(day=word2_day)
        if(header2==None):
            header2=None

    else:
        word2=None        


    word_e1 = the_economy_word_list1.objects.values('word','meaning','example','word_img','synonym').filter(day=word_e1_day)
    word_e2 = the_economy_word_list2.objects.values('word','meaning','example','word_img','synonym').filter(day=word_e2_day)
        
    if(word_e1.count()>0):
        e=1
        header_e1 = the_economy_word_Header1.objects.values('Heading_for_list1','link').filter(day=word_e1_day)
        if(header_e1==None):
            header_e1=None
    else:
        word_e1=None        
    if(word_e2.count()>0):
        e=2
        header_e2 = the_economy_word_Header2.objects.values('Heading_for_list2','link').filter(day=word_e2_day)
            
        if(header_e2==None):
            header_e2=None
    else:
        word_e2=None

    jobs = job.objects.values('extra_day','first_day','last_day','heading','eligibility','age','amount','day','new_id','des','ca_img').filter(home=True).order_by('-day','-creation_time')

    mathh = math.objects.values().filter(home=True).all().order_by('day','creation_time')[:4]
    reasoningh = reasoning.objects.values().filter(home=True).all().order_by('day','creation_time')
    cloze = close.objects.values('question','page').filter(home=True).order_by('day','creation_time')
    print(mathh)


        
    if request.method == 'POST':
        form = UserForm(request.POST)
        if form.is_valid():
            user = form.save(commit=False)
            username = form.cleaned_data['username']
            password = form.cleaned_data['password']
            user.set_password(password)
            user.save()
            user = authenticate(username=username, password=password)
            if user is not None:
                if user.is_active:
                    auth_login(request, user)
                    j = {
                        "r": "home/car.html",
                        "form": form
                    }
                    context = {
                            "form": form,
                            }
                    slide = currentaffairs_descriptive.objects.values('upper_heading','yellow_heading','key_1','key_2','key_3','day','new_id','paragraph','all_key_points','ca_img').filter(is_live=True).order_by('-id')[:10][::-1]
                    return HttpResponseRedirect('/')
        context = {
            "form": form,
        }
        return render(request, 'home/car.html', context)

   
    else:
        slide = currentaffairs_descriptive.objects.values('link','url','upper_heading','yellow_heading','key_1','key_2','key_3','day','new_id','paragraph','all_key_points','ca_img').filter(is_live=True).order_by('-day')[:10]
        return render(request,'home/new.html',{'close':cloze,'job': jobs,'reasoning':reasoningh,'math':mathh,'word_e2_day':word_e2_day,'word_e1_day':word_e1_day,'word2_day':word2_day,'word1_day':word1_day,'word1':word1,'word_e1':word_e1,'word2':word2,'word_e2':word_e2,'header1':header1,'header2':header2,'header_e1':header_e1,'header_e2':header_e2,'p':'','slide': slide,'form':userform,'login':login})


def ca(request,user_year_month,user_page_no):
    userform = UserForm(request.POST or None)
    tag_page=user_year_month
    user_year_month=user_year_month.replace('current-affairs-','')
    user_year_month=user_year_month.split('-')
    category=0
    today=0
    user_month='January'
    page_var='January_page'#just emni emni ...only for mcq category initilization
    if "category"  in user_year_month:
        category=1
        user_year=user_year_month[1]
        user_category=user_year
        user_category=user_category.replace("-","_")
        obj=total.objects.values(user_category)
        t= int(obj[0][user_category])
        print('cat'+str(t))
        #t=int(obj[0].total_current_affairs_page)
    elif "today"  in user_year_month:
        today=1
        user_year=user_year_month[1]
        obj=total.objects.all()
        t=int(obj[0].total_current_affairs_page)
        print('cat'+str(t))
        #t=int(obj[0].total_current_affairs_page)
        
    else:    
        user_month=user_year_month[0].title()
        user_year=user_year_month[1]
        month_real=user_month
        if(month_real =='January'):     
            user_date='01'
        elif(month_real == 'February'):
            user_date='02'
        elif(month_real =='March'):
            user_date='03'
        elif(month_real =='April'):
            user_date='04'
        elif(month_real =='May'):
            user_date='05'
        elif(month_real =='June'):
            user_date='06'
        elif(month_real =='July'):
            user_date='07'
        elif(month_real =='August'):
            user_date='08'
        elif(month_real =='September'):
            user_date='09'
        elif(month_real =='October'):
            user_date='10'
        elif(month_real =='November'):
            user_date='11'
        elif(month_real =='December'):
            user_date='12'   
        user_date=user_year+'-'+user_date+'-'+user_page_no
        print('dat='+user_date)
        print('year='+user_year)
        print('month='+user_month)
        page_var=user_month.title() +'_page'
        if user_year=='2018':     
            obj=currentaffairs_descriptive_info_2018.objects.values(page_var)
            t= int(obj[0][page_var])
            print('date wise'+ str(t))
        elif user_year=='2019':     
            obj=currentaffairs_descriptive_info_2019.objects.values(page_var)
            t= int(obj[0][page_var])
            print('date wise 2019'+ str(t))
    page=['2','3']
    login = Login(request.POST or None)
    #name = NameForm(request.POST or None)

django/django_project/bank/templates/acc_active_email.html
{% autoescape off %}
 atyle="color:green">Hi {{ user.username }},
Please click on the link to confirm your registration,

http://{{ domain }}{% url 'bank:activate' uidb64=uid token=token %}
{% endautoescape %}

django/django_project/bank/templates/login.html
<!DOCTYPE html>
<html lang="en">
<head>
  <title>Bootstrap Example</title>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
 
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
  
  

   {% load static %}
 

<link rel="stylesheet" href="{% static 'css/pratima.css' %}" />

<style>
  
 

  </style>
</head>
<body>

 <nav class="navbar navbar-default">
                        <div class="container-fluid">
                            <div class="navbar-header">
                                <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
                                    <span class="sr-only">Toggle navigation</span>
                                    <span class="icon-bar"></span>
                                    <span class="icon-bar"></span>
                                    <span class="icon-bar"></span>
                                </button>
                                <a class="navbar-brand" href="#">Rocky Balbo</a>
                            </div>
                            <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
                                <ul class="nav navbar-nav navbar-right">
                                    <li class="dropdown">
                                        <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">Account
                                            <span class="caret"></span>
                                        </a>
                                        <ul class="dropdown-menu" role="menu">
                                            <li>
                                                <a href="/home">home</a>
                                            </li>
                                            <li>
                                                <a href="#">Another action</a>
                                            </li>
                                            <li>
                                                <a href="#">Something else here</a>
                                            </li>
                                            <li class="divider"></li>
                                            <li>
                                                <a href="#">Separated link</a>
                                            </li>
                                            <li class="divider"></li>
                                            <li>
                                                <a href="/logout">Logout</a>
                                            </li>
                                        </ul>
                                    </li>
                                </ul>
                            </div>
                        </div>
                    </nav>
					
					
					<div class="container">
    <div class="row">
        <div class="col-md-4 col-md-offset-4">
            <div class="login-panel panel panel-default">
                <div class="panel-heading">
                    <h3 class="panel-title">Please Sign In</h3>
                </div>
                <div class="panel-body">
                    <form method="post" action="{% url 'django.contrib.auth.views.login' %}">

								{{ form}}
						
                        <p class="bs-component">
                            <center>
                                <input class="btn btn-success btn-sm" type="submit" value="login" />
                            </center>
                        </p>
                        <input type="hidden" name="next" value="{{ next }}" />
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>




</body>
</html>